// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qydkezeghsmbyrbnvpmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5ZGtlemVnaHNtYnlyYm52cG1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTk3NDksImV4cCI6MjA3MDc3NTc0OX0.YjfwdPpDWOpNtKZ6_oN7ISdwS-O7pmLkWu0kV1eeC9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});